SELECT = 'SELECT'
FROM = 'FROM'
JOIN = 'JOIN'
ON = 'ON'
WHERE = 'WHERE'
INNER = 'INNER'
LEFT = 'LEFT'
RIGHT = 'RIGHT'
OUTER = 'OUTER'
ORDER_BY = 'ORDER BY'
DESC = 'DESC'
INSERT_INTO = 'INSERT INTO'
VALUES = 'VALUES'

COMMAND_TMPL = '%s %s '
STRING_TMPL = '"%s"'
CONDITION_TMPL = '(%s %s %s)'

SUBSTITUTION_TMPL = '%s'

VALIDATED_OPERATIONS = {'join', 'on', 'sql'}

NEXT_OPERATION = {
}

PREVIOUS_OPERATION = {
}

SELECT_QUERY_TYPE = 0
INSERT_QUERY_TYPE = 1
CREATE_QUERY_TYPE = 2
