ALL_FIELDS_SELECTOR = '*'
FIELDS_SPLITTER = ', '
TABLES_SPLITTER = ', '
CONDITIONS_SPLITTER = ' AND '

ORDERING_FIELDS_TMPL = '%s %s'
INSERTION_TMPL = '%s (%s)'
VALUES_TMPL = '(%s)'


INNER_JOIN_TYPE = 0
OUTER_JOIN_TYPE = 1
LEFT_JOIN_TYPE = 2
RIGHT_JOIN_TYPE = 3
